:-encoding(utf8).

phrase(W) :-
  set_prolog_stack(global, limit(100 000 000 000)),
  findall(X,s(X,Y,Z),L),
  % random_member(W,L).
  open('liste.txt',write,OS),
  loop_through_list(L,OS),
  close(OS).

loop_through_list([],OS).
loop_through_list([Head|Tail],OS) :-
    write(OS,Head),
    write(OS,'\n'),
    loop_through_list(Tail,OS).

queue(Tail,[Head|Tail]).

head(Head,[Head|Tail]).

s(L,P,Q):-
  sn(SN,P,X,N,G,H,_),
  sv(SV,X,Q,N,H,Ho,J),
  queue(C,SN),
  head(Head,C),
  relsem(agent,Head,J),
  \+nth0(Z, SV, SN),
  append(SN,SV,L).
  % atomic_list_concat(L,' ',A).

sn([DET,NOM],P,Q,N,G,H,W):-
  det(DET,P,X,N,G,W),
  n(NOM,X,Y,N,G,H).

% sn([NP],P,Q,N,G,H):-
%   np(NP,P,X,N,G,H).

% sv([VI],P,Q,N,H,Ho):-vi(VI,P,Q,N,H).

sv(L,P,Q,N,H,Ho,I):-
  vt(VT,P,X,N,H,Ho,I),
  sn(SN,X,Q,No,G,Ho,qu),
  queue(Z,SN),
  head(Head,Z),
  relsem(patient,Head,I),
  append([VT],SN,L).

det(la,P,Q,sing,fem,nq).
det(le,P,Q,sing,masc,nq).
det(les,P,Q,plur,_,nq).
det(tout,P,Q,sing,masc,qu).
det(toute,P,Q,sing,fem,qu).
det(tous,P,Q,plur,masc,qu).
det(toutes,P,Q,plur,fem,qu).
det(chaque,P,Q,sing,_,qu).
det(quelque,P,Q,sing,_,qu).
det(quelques,P,Q,plur,_,qu).
det(certain,P,Q,sing,masc,qu).
det(certaine,P,Q,sing,fem,qu).
det(certains,P,Q,plur,masc,qu).
det(certaines,P,Q,plur,fem,qu).

vt(abandonne,P,Q,sing,hum,X,abandonner).
vt(abandonnent,P,Q,plur,hum,X,abandonner).
vt(affronte,P,Q,sing,hum,hum,affronter).
vt(affrontent,P,Q,plur,hum,hum,affronter).
vt(attaque,P,Q,sing,hum,X,attaquer).
vt(attaquent,P,Q,plur,hum,X,attaquer).
vt(attrape,P,Q,sing,hum,X,attraper).
vt(attrapent,P,Q,plur,hum,X,attraper).
vt(avance,P,Q,sing,hum,nhum,avancer).
vt(avancent,P,Q,plur,hum,nhum,avancer).
vi(avance,P,Q,sing,hum,avancer).
vi(avancent,P,Q,plur,hum,avancer).
vt(ont,P,Q,plur,hum,nhum,avoir).
vi(appartient,P,Q,sing,hum,appartenir).
vi(appartiennent,P,Q,plur,hum,appartenir).
vi(arrête,P,Q,sing,hum,arrêter).
vi(arrêtent,P,Q,plur,hum,arrêter).
vt(arrête,P,Q,sing,hum,nhum,arrêter).
vt(arrêtent,P,Q,plur,hum,nhum,arrêter).
vt(danse,P,Q,sing,hum,nhum,danser).
vt(dansent,P,Q,plur,hum,nhum,danser).
vi(danse,P,Q,sing,hum,danser).
vt(domine,P,Q,sing,hum,X,dominer).
vt(dominent,P,Q,plur,hum,X,dominer).
vt(joue,P,Q,sing,hum,nhum,jouer).
vt(jouent,P,Q,plur,hum,nhum,jouer).
vi(joue,P,Q,sing,hum,jouer).
vi(jouent,P,Q,plur,hum,jouer).
vi(progresse,P,Q,sing,hum,progresser).
vi(progressent,P,Q,plur,hum,pregresser).
vt(prend,P,Q,sing,hum,X,prendre).
vt(prennent,P,Q,plur,hum,X,prendre).
vi(prend,P,Q,sing,hum,prendre).
vi(prennent,P,Q,plur,hum,prendre).
vt(pratique,P,Q,sing,hum,nhum),pratiquer.
vt(pratiquent,P,Q,plur,hum,nhum,pratiquer).
vt(remplace,P,Q,sing,hum,hum,remplacer).
vt(remplacent,P,Q,plur,hum,hum,remplacer).
vt(remporte,P,Q,sing,hum,nhum,remporter).
vt(remportent,P,Q,plur,hum,nhum,remporter).
vt(rencontre,P,Q,sing,hum,hum,rencontrer).
vt(rencontrent,P,Q,plur,hum,hum,rencontrer).
vt(siffle,P,Q,sing,hum,hum,siffler).
vt(sifflent,P,Q,plur,hum,hum,siffler).
vi(siffle,P,Q,sing,hum,siffler).
vi(sifflent,P,Q,plur,hum,siffler).
vt(stoppe,P,Q,sing,hum,X,stopper).
vt(stoppent,P,Q,plur,hum,X,stopper).
vi(stoppe,P,Q,sing,hum,stopper).
vi(stoppent,P,Q,plur,hum,stopper).
vi(sue,P,Q,sing,hum,suer).
vi(suent,P,Q,plur,hum,suer).
vt(suit,P,Q,sing,hum,hum,suivre).
vt(suivent,P,Q,plur,hum,hum,suivre).
vi(suit,P,Q,sing,hum,suivre).
vi(suivent,P,Q,plur,hum,suivre).
vt(bat,P,Q,sing,hum,hum,battre).
vt(battent,P,Q,plur,hum,hum,battre).
vi(bat,P,Q,sing,hum,battre).
vi(battent,P,Q,plur,hum,battre).
vt(blesse,P,Q,sing,hum,hum,blesser).
vt(blessent,P,Q,plur,hum,hum,blesser).
vt(bloque,P,Q,sing,hum,Y,bloquer).
vt(bloquent,P,Q,plur,hum,Y,bloquer).
vt(boit,P,Q,sing,hum,nhum,boire).
vt(boivent,P,Q,plur,hum,nhum,boire).
vt(bouscule,P,Q,sing,hum,hum,bousculer).
vt(bousculent,P,Q,plur,hum,hum,bousculer).
vt(contre,P,Q,sing,hum,X,contrer).
vt(contrent,P,Q,plur,hum,X,contrer).
vi(court,P,Q,sing,hum,courir).
vi(courent,P,Q,plur,hum,courir).
vt(fait,P,Q,sing,hum,nhum,faire).
vt(font,P,Q,plur,hum,nhum,faire).
vt(fatigue,P,Q,sing,hum,hum,fatiguer).
vt(fatiguent,P,Q,plur,hum,hum,fatiguer).
vi(fatigue,P,Q,sing,hum,fatiguer).
vi(fatiguent,P,Q,plur,hum,fatiguer).
vt(frappe,P,Q,sing,hum,X,frapper).
vt(frappent,P,Q,plur,hum,X,frapper).
vt(gagne,P,Q,sing,hum,nhum,gagner).
vt(gagnent,P,Q,plur,hum,nhum,gagner).
vi(marche,P,Q,sing,hum,marcher).
vi(marchent,P,Q,plur,hum,marcher).
vt(marque,P,Q,sing,hum,hum,marquer).
vt(marquent,P,Q,plur,hum,hum,marquer).
vi(marque,P,Q,sing,hum,marquer).
vi(marquent,P,Q,plur,hum,marquer).
vt(vainc,P,Q,sing,hum,hum,vaincre).
vt(vainquent,P,Q,plur,hum,hum,vaincre).
vt(vise,P,Q,sing,hum,nhum,viser).
vt(visent,P,Q,plur,hum,nhum,viser).
vt(tire,P,Q,sing,hum,nhum,tirer).
vt(tirent,P,Q,plur,hum,nhum,tirer).
vt(touche,P,Q,sing,hum,Y,toucher).
vt(touchent,P,Q,plur,hum,Y,toucher).

relsem(patient,concurrent,battre).
relsem(patient,adversaire,battre).
relsem(patient,adversaire,attaquer).
relsem(patient,but,marquer).
relsem(patient,point,marquer).
relsem(agent,sportif,abandonner).
relsem(agent,sportifs,abandonner).
relsem(agent,cheval,courir).
relsem(agent,sportif,courir).
relsem(agent,sportifs,courir).
relsem(patient,essai,marquer).
relsem(agent,vainqueur,gagner).
relsem(agent,gagnant,gagner).
relsem(agent,sportif,gagner).
relsem(agent,sportifs,gagner).
relsem(agent,marathonien,courir).
relsem(agent,sportif,jouer).
relsem(agent,sportifs,jouer).
relsem(agent,sprinter,courir).
relsem(agent,sportif,battre).
relsem(agent,sportif,rencontrer).
relsem(agent,sportifs,battre).
relsem(agent,sportifs,rencontrer).
relsem(patient,course,courir).
relsem(patient,courses,courir).
relsem(patient,marathon,courir).
relsem(agent,concurrent,vaincre).
relsem(agent,sportif,vaincre).
relsem(agent,sportifs,vaincre).
relsem(agent,attaquant,attaquer).
relsem(patient,juge,toucher).
relsem(patient,adversaire,vaincre).
relsem(agent,basketteur,courir).
relsem(agent,cheval,marcher).
relsem(agent,juge,jouer).
relsem(agent,juge,courir).
relsem(agent,juge,marcher).
relsem(patient,judo,pratiquer).
relsem(patient,natation,pratiquer).
relsem(agent,sportif,pratiquer).
relsem(agent,sportifs,pratiquer).
relsem(patient,golf,pratiquer).
relsem(patient,sport,pratiquer).
relsem(patient,sports,pratiquer).
relsem(patient,tennis,pratiquer).
relsem(agent,champion,gagner).
relsem(agent,championne,gagner).
relsem(patient,partie,jouer).
relsem(patient,boxeur,vaincre).
relsem(agent,vainqueur,vaincre).
relsem(agent,vainqueur,pratiquer).
relsem(agent,vainqueur,jouer).
relsem(agent,footballer,marquer).
relsem(agent,judoka,vaincre).
relsem(agent,footballeur,marquer).
relsem(agent,footballeur,courir).
relsem(agent,footballer,courir).
relsem(agent,footballeuse,courir).
relsem(patient,basketteur,marquer).
relsem(patient,adversaire,marquer).
relsem(agent,basketteur,marquer).
relsem(agent,footballeuse,marquer).
relsem(agent,footballeuse,tirer).
relsem(agent,footballeuse,jouer).
relsem(agent,footballer,tirer).
relsem(agent,footballer,jouer).
relsem(agent,footballeur,tirer).
relsem(agent,footballeur,jouer).
relsem(agent,joueuse,gagner).
relsem(agent,joueuse,jouer).
relsem(patient,joueuse,jouer).
relsem(agent,joueuse,vaincre).
relsem(agent,joueurs,vaincre).
relsem(agent,joueur,vaincre).
relsem(agent,joueur,abandonner).
relsem(agent,joueurs,abandonner).
relsem(agent,joueuse,abandonner).
relsem(patient,joueur,jouer).
relsem(agent,joueur,battre).
relsem(agent,joueuse,battre).
relsem(patient,joueurs,jouer).
relsem(agent,joueurs,battre).
relsem(agent,joueur,jouer).
relsem(agent,joueurs,jouer).
relsem(agent,joueur,gagner).
relsem(agent,joueurs,gagner).
relsem(patient,joueur,stopper).
relsem(patient,joueurs,stopper).


n(sport,P,Q,sing,masc,nhum).
n(sports,P,Q,plur,masc,nhum).
n(jiujitsu,P,Q,sing,masc,nhum).
% n(contre-offensive,P,Q,sing,fem,nhum).
n(snowboard,P,Q,sing,masc,nhum).
n(skieur,P,Q,sing,masc,hum).
n(concurrent,P,Q,sing,masc,hum).
n(patineur,P,Q,sing,masc,hum).
n(prise,P,Q,sing,fem,nhum).
n(tricheur,P,Q,sing,masc,hum).
n(marathon,P,Q,sing,masc,nhum).
n(relayeur,P,Q,sing,masc,hum).
% n(arbitre,P,Q,sing,masc,hum).
n(goal,P,Q,sing,masc,nhum).
n(footballer,P,Q,sing,masc,nhum).
n(régate,P,Q,sing,fem,nhum).
n(balle,P,Q,sing,masc,nhum).
n(ballon,P,Q,sing,masc,nhum).
n(hooligan,P,Q,sing,masc,hum).
n(tension,P,Q,sing,fem,nhum).
n(cible,P,Q,sing,fem,nhum).
n(feinte,P,Q,sing,fem,nhum).
n(basket,P,Q,sing,masc,nhum).
n(courses,P,Q,plur,fem,nhum).
n(batte,P,Q,sing,fem,nhum).
n(haies,P,Q,plur,fem,nhum).
n(selles,P,Q,plur,fem,nhum).
n(favori,P,Q,sing,masc,nhum).
n(club,P,Q,sing,masc,nhum).
n(taekwendo,P,Q,sing,masc,nhum).
n(prolongation,P,Q,sing,fem,nhum).
n(tournoi,P,Q,sing,masc,nhum).
n(faute,P,Q,sing,fem,nhum).
n(dégagement,P,Q,sing,masc,nhum).
n(volleyeuse,P,Q,sing,fem,hum).
n(clubs,P,Q,plur,masc,nhum).
n(essai,P,Q,sing,masc,nhum).
n(freestyle,P,Q,sing,masc,nhum).
n(coach,P,Q,sing,masc,hum).
n(bloqueur,P,Q,sing,masc,hum).
n(match,P,Q,sing,masc,nhum).
n(défaite,P,Q,sing,fem,nhum).
n(boxe,P,Q,sing,fem,nhum).
n(touchdown,P,Q,sing,masc,nhum).
n(égalité,P,Q,sing,fem,nhum).
n(défense,P,Q,sing,fem,nhum).
n(marathonien,P,Q,sing,masc,hum).
n(riposte,P,Q,sing,fem,nhum).
n(plaquage,P,Q,sing,masc,nhum).
n(ailier,P,Q,sing,masc,hum).
n(prolongations,P,Q,plur,fem,nhum).
n(frappe,P,Q,sing,fem,nhum).
n(dopage,P,Q,sing,masc,nhum).
n(supporteur,P,Q,sing,masc,hum).
n(stade,P,Q,sing,masc,nhum).
n(podiums,P,Q,plur,masc,nhum).
n(contre,P,Q,sing,masc,nhum).
n(terrain,P,Q,sing,masc,nhum).
n(partie,P,Q,sing,fem,nhum).
n(échauffement,P,Q,sing,masc,nhum).
n(point,P,Q,sing,masc,nhum).
n(libero,P,Q,sing,masc,hum).
n(volley,P,Q,sing,masc,nhum).
n(but,P,Q,sing,masc,nhum).
n(participant,P,Q,sing,masc,hum).
n(joueuse,P,Q,sing,fem,hum).
n(sportive,P,Q,sing,fem,hum).
n(relais,P,Q,sing,masc,nhum).
n(nul,P,Q,sing,masc,nhum).
n(tricherie,P,Q,sing,fem,nhum).
n(interdits,P,Q,plur,masc,nhum).
n(passe,P,Q,sing,fem,nhum).
n(capitaine,P,Q,sing,masc,hum).
n(gardien,P,Q,sing,masc,hum).
n(pivot,P,Q,sing,masc,nhum).
n(golf,P,Q,sing,masc,nhum).
n(crampon,P,Q,sing,masc,nhum).
n(sprint,P,Q,sing,masc,nhum).
n(champion,P,Q,sing,masc,hum).
n(boxeur,P,Q,sing,masc,hum).
n(basketball,P,Q,sing,masc,nhum).
n(duel,P,Q,sing,masc,nhum).
n(joueurs,P,Q,plur,masc,hum).
n(amateurs,P,Q,plur,masc,hum).
n(dunk,P,Q,sing,fem,nhum).
n(trophée,P,Q,sing,masc,nhum).
n(football,P,Q,sing,masc,nhum).
n(sprinter,P,Q,sing,masc,nhum).
n(tennis,P,Q,sing,masc,nhum).
n(handballeur,P,Q,sing,masc,hum).
n(plaqueur,P,Q,sing,masc,hum).
n(crampe,P,Q,sing,fem,nhum).
n(rencontre,P,Q,sing,fem,nhum).
n(championnat,P,Q,sing,masc,nhum).
n(score,P,Q,sing,masc,nhum).
n(smash,P,Q,sing,masc,nhum).
n(sumotori,P,Q,sing,masc,hum).
n(footeux,P,Q,sing,masc,hum).
n(sifflet,P,Q,sing,masc,nhum).
n(blocage,P,Q,sing,masc,nhum).
n(sportif,P,Q,sing,masc,hum).
n(filets,P,Q,plur,masc,nhum).
n(pelouse,P,Q,sing,masc,nhum).
n(set,P,Q,sing,masc,nhum).
n(compétition,P,Q,sing,fem,nhum).
n(sprinteur,P,Q,sing,masc,hum).
n(course,P,Q,sing,fem,nhum).
n(ligue,P,Q,sing,fem,nhum).
n(jeux,P,Q,plur,masc,nhum).
n(défenseur,P,Q,sing,masc,hum).
n(buteur,P,Q,sing,masc,hum).
n(débutant,P,Q,sing,masc,hum).
n(filet,P,Q,sing,masc,hum).
n(foot,P,Q,sing,masc,nhum).
n(compétiteur,P,Q,sing,masc,hum).
n(médaille,P,Q,sing,fem,nhum).
n(judo,P,Q,sing,masc,nhum).
n(juge,P,Q,sing,masc,hum).
n(triche,P,Q,sing,fem,nhum).
n(challenger,P,Q,sing,masc,hum).
n(touche,P,Q,sing,fem,nhum).
n(vainqueur,P,Q,sing,masc,hum).
n(rotation,P,Q,sing,fem,nhum).
n(finale,P,Q,sing,fem,nhum).
n(judoka,P,Q,sing,fem,hum).
n(victoire,P,Q,sing,fem,nhum).
n(provocation,P,Q,sing,fem,nhum).
n(coaching,P,Q,sing,masc,nhum).
n(poulain,P,Q,sing,masc,hum).
n(gymnase,P,Q,sing,masc,nhum).
n(centre,P,Q,sing,masc,nhum).
n(adversaire,P,Q,sing,masc,hum).
n(manager,P,Q,sing,masc,hum).
n(performance,P,Q,sing,fem,nhum).
n(transfert,P,Q,sing,masc,nhum).
n(joueur,P,Q,sing,masc,hum).
n(réception,P,Q,sing,fem,nhum).
n(handball,P,Q,sing,masc,nhum).
n(remplaçant,P,Q,sing,masc,hum).
n(qualification,P,Q,sing,fem,nhum).
n(professionnel,P,Q,sing,masc,hum).
n(disqualification,P,Q,sing,fem,nhum).
n(supportrice,P,Q,sing,fem,hum).
n(entraîneur,P,Q,sing,masc,hum).
n(courbature,P,Q,sing,fem,nhum).
n(vitesse,P,Q,sing,fem,nhum).
n(pilote,P,Q,sing,masc,hum).
n(lancer,P,Q,sing,masc,nhum).
n(dribbleur,P,Q,sing,masc,hum).
n(podium,P,Q,sing,masc,nhum).
n(milieu,P,Q,sing,masc,nhum).
n(sportives,P,Q,plur,fem,hum).
n(meneur,P,Q,sing,masc,hum).
n(poteaux,P,Q,plur,masc,nhum).
n(lancers,P,Q,plur,masc,nhum).
n(entraineuse,P,Q,sing,fem,hum).
n(supporteurs,P,Q,plur,masc,hum).
n(rugby,P,Q,sing,masc,nhum).
n(corner,P,Q,sing,masc,nhum).
n(attaquant,P,Q,sing,masc,hum).
n(surface,P,Q,sing,fem,nhum).
n(olympiades,P,Q,plur,fem,nhum).
n(parade,P,Q,sing,fem,nhum).
n(sportifs,P,Q,plur,masc,hum).
n(concours,P,Q,plur,masc,nhum).
n(repos,P,Q,sing,masc,nhum).
n(footballeuse,P,Q,sing,fem,hum).
n(talonneur,P,Q,sing,masc,hum).
n(golfeur,P,Q,sing,masc,hum).
n(balayage,P,Q,sing,masc,nhum).
n(supporteur,P,Q,sing,masc,hum).
n(rugbyman,P,Q,sing,masc,hum).
n(skieur,P,Q,sing,masc,hum).
n(natation,P,Q,sing,fem,nhum).
n(ascension,P,Q,sing,fem,nhum).
n(olympiade,P,Q,sing,fem,nhum).
n(cheval,P,Q,sing,masc,hum).
n(chrono,P,Q,sing,masc,nhum).
n(sumo,P,Q,plur,masc,hum).
n(gagnant,P,Q,sing,masc,nhum).
n(playoffs,P,Q,plur,masc,nhum).
n(entraineur,P,Q,sing,masc,hum).
n(footballeur,P,Q,sing,masc,hum).
n(spectateur,P,Q,sing,masc,hum).
n(basketteur,P,Q,sing,masc,hum).
n(tournois,P,Q,plur,masc,nhum).
n(perdant,P,Q,sing,masc,nhum).
n(fatigue,P,Q,sing,fem,nhum).
n(pénalty,P,Q,sing,masc,nhum).
n(championne,P,Q,sing,fem,hum).
n(tir,P,Q,sing,masc,nhum).
n(tirs,P,Q,plur,masc,nhum).


np(Porsche,P,Q,sing,fem,nhum).
np(NFL,P,Q,sing,masc,nhum).
np(Belgique,P,Q,sing,fem,nhum).
np(Grèce,P,Q,sing,fem,nhum).
np(Ferrari,P,Q,sing,fem,nhum).
np(Tunisie,P,Q,sing,fem,nhum).
np(Australie,P,Q,sing,fem,nhum).
np(Galatasaray,P,Q,sing,masc,nhum).
np(Espagne,P,Q,sing,fem,hum).
np(France,P,Q,sing,masc,hum).
np(BMX,P,Q,sing,masc,nhum).
np(Bastia,P,Q,sing,masc,nhum).
np(Angleterre,P,Q,sing,fem,hum).
np(ULM,P,Q,sing,masc,nhum).
np(Allemagne,P,Q,sing,fem,nhum).
np(Inde,P,Q,sing,fem,nhum).
np(Canada,P,Q,sing,masc,nhum).
np(Brennus,P,Q,sing,masc,nhum).
np(Panthéon,P,Q,sing,masc,nhum).
np(Suisse,P,Q,sing,fem,hum).
np(Wimbledon,P,Q,sing,masc,nhum).
np(Italie,P,Q,sing,masc,nhum).
np(F1,P,Q,sing,fem,nhum).
np(Paris,P,Q,sing,masc,hum).
np(Pakistan,P,Q,sing,masc,nhum).
np(Poulidor,P,Q,sing,masc,hum).
np(Monaco,P,Q,sing,masc,nhum).
np(Londres,P,Q,sing,masc,nhum).
np(JO,P,Q,plur,fem,nhum).
